"""
Base de dados de celulares para recomendação.
Contém informações detalhadas sobre diversos modelos.
"""

PHONES = [
    # Samsung
    {
        "id": 1,
        "nome": "Samsung Galaxy S24 Ultra",
        "marca": "Samsung",
        "preco": 8499,
        "ano_lancamento": 2024,
        "tela": 6.8,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 200,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g.jpg",
        "descricao": "O topo de linha da Samsung com S Pen integrada, câmera de 200MP e tela AMOLED de 6.8 polegadas."
    },
    {
        "id": 2,
        "nome": "Samsung Galaxy S24",
        "marca": "Samsung",
        "preco": 5499,
        "ano_lancamento": 2024,
        "tela": 6.2,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4000,
        "camera_principal": 50,
        "processador": "Exynos 2400",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g.jpg",
        "descricao": "Compacto e poderoso, com IA integrada e Galaxy AI para produtividade."
    },
    {
        "id": 3,
        "nome": "Samsung Galaxy A55",
        "marca": "Samsung",
        "preco": 2799,
        "ano_lancamento": 2024,
        "tela": 6.6,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Exynos 1480",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg",
        "descricao": "Intermediário premium com tela Super AMOLED e resistência à água IP67."
    },
    {
        "id": 4,
        "nome": "Samsung Galaxy A35",
        "marca": "Samsung",
        "preco": 1999,
        "ano_lancamento": 2024,
        "tela": 6.6,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Exynos 1380",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg",
        "descricao": "Ótimo custo-benefício com tela AMOLED de 120Hz e bateria de longa duração."
    },
    {
        "id": 5,
        "nome": "Samsung Galaxy A15",
        "marca": "Samsung",
        "preco": 1099,
        "ano_lancamento": 2024,
        "tela": 6.5,
        "ram": 4,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Helio G99",
        "sistema": "Android 14",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15.jpg",
        "descricao": "Entrada com tela AMOLED grande e bateria generosa para o dia todo."
    },
    # Apple
    {
        "id": 6,
        "nome": "iPhone 15 Pro Max",
        "marca": "Apple",
        "preco": 9999,
        "ano_lancamento": 2023,
        "tela": 6.7,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 4441,
        "camera_principal": 48,
        "processador": "A17 Pro",
        "sistema": "iOS 17",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
        "descricao": "O iPhone mais avançado com chip A17 Pro, titânio e câmera periscópio com zoom 5x."
    },
    {
        "id": 7,
        "nome": "iPhone 15",
        "marca": "Apple",
        "preco": 6499,
        "ano_lancamento": 2023,
        "tela": 6.1,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 3349,
        "camera_principal": 48,
        "processador": "A16 Bionic",
        "sistema": "iOS 17",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
        "descricao": "Design com Dynamic Island, câmera de 48MP e conector USB-C."
    },
    {
        "id": 8,
        "nome": "iPhone 14",
        "marca": "Apple",
        "preco": 4999,
        "ano_lancamento": 2022,
        "tela": 6.1,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 3279,
        "camera_principal": 12,
        "processador": "A15 Bionic",
        "sistema": "iOS 16",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg",
        "descricao": "Design elegante com detecção de acidentes e modo Ação para vídeos estabilizados."
    },
    {
        "id": 9,
        "nome": "iPhone SE (2022)",
        "marca": "Apple",
        "preco": 3499,
        "ano_lancamento": 2022,
        "tela": 4.7,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 2018,
        "camera_principal": 12,
        "processador": "A15 Bionic",
        "sistema": "iOS 15",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg",
        "descricao": "iPhone compacto e acessível com chip potente e Touch ID."
    },
    # Xiaomi
    {
        "id": 10,
        "nome": "Xiaomi 14 Ultra",
        "marca": "Xiaomi",
        "preco": 7499,
        "ano_lancamento": 2024,
        "tela": 6.73,
        "ram": 16,
        "armazenamento": 512,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg",
        "descricao": "Câmera Leica profissional com sensor de 1 polegada e gravação 8K."
    },
    {
        "id": 11,
        "nome": "Xiaomi 14",
        "marca": "Xiaomi",
        "preco": 4999,
        "ano_lancamento": 2024,
        "tela": 6.36,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 4610,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg",
        "descricao": "Compacto premium com câmera Leica e tela LTPO AMOLED de 120Hz."
    },
    {
        "id": 12,
        "nome": "Xiaomi Redmi Note 13 Pro",
        "marca": "Xiaomi",
        "preco": 2299,
        "ano_lancamento": 2024,
        "tela": 6.67,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5100,
        "camera_principal": 200,
        "processador": "Snapdragon 7s Gen 2",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-5g.jpg",
        "descricao": "Câmera de 200MP incrível em um intermediário com carregamento de 67W."
    },
    {
        "id": 13,
        "nome": "Xiaomi Redmi Note 13",
        "marca": "Xiaomi",
        "preco": 1499,
        "ano_lancamento": 2024,
        "tela": 6.67,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 108,
        "processador": "Snapdragon 685",
        "sistema": "Android 13",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-4g.jpg",
        "descricao": "Tela AMOLED de 120Hz com câmera de 108MP a um preço acessível."
    },
    {
        "id": 14,
        "nome": "Xiaomi POCO X6 Pro",
        "marca": "Xiaomi",
        "preco": 2499,
        "ano_lancamento": 2024,
        "tela": 6.67,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 64,
        "processador": "Dimensity 8300 Ultra",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro-5g.jpg",
        "descricao": "Performance de flagship com carregamento turbo de 67W e tela Flow AMOLED."
    },
    # Motorola
    {
        "id": 15,
        "nome": "Motorola Edge 50 Ultra",
        "marca": "Motorola",
        "preco": 5499,
        "ano_lancamento": 2024,
        "tela": 6.7,
        "ram": 16,
        "armazenamento": 512,
        "bateria": 4500,
        "camera_principal": 50,
        "processador": "Snapdragon 8s Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg",
        "descricao": "Acabamento em madeira ou couro, câmera periscópio e tela pOLED de 144Hz."
    },
    {
        "id": 16,
        "nome": "Motorola Edge 40 Neo",
        "marca": "Motorola",
        "preco": 2499,
        "ano_lancamento": 2023,
        "tela": 6.55,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Dimensity 7030",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-40-neo.jpg",
        "descricao": "Intermediário elegante com tela pOLED de 144Hz e carregamento de 68W."
    },
    {
        "id": 17,
        "nome": "Motorola Moto G84",
        "marca": "Motorola",
        "preco": 1799,
        "ano_lancamento": 2023,
        "tela": 6.55,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Snapdragon 695",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g84.jpg",
        "descricao": "Tela pOLED em intermediário com som estéreo Dolby Atmos e design fino."
    },
    {
        "id": 18,
        "nome": "Motorola Moto G54",
        "marca": "Motorola",
        "preco": 1299,
        "ano_lancamento": 2023,
        "tela": 6.5,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Dimensity 7020",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g54-5g.jpg",
        "descricao": "5G acessível com som estéreo e bateria para dois dias de uso."
    },
    {
        "id": 19,
        "nome": "Motorola Moto E22",
        "marca": "Motorola",
        "preco": 799,
        "ano_lancamento": 2022,
        "tela": 6.5,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 4020,
        "camera_principal": 16,
        "processador": "Helio G37",
        "sistema": "Android 12",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-e22.jpg",
        "descricao": "Smartphone básico e confiável para tarefas do dia a dia com tela de 90Hz."
    },
    # Google Pixel
    {
        "id": 20,
        "nome": "Google Pixel 8 Pro",
        "marca": "Google",
        "preco": 6999,
        "ano_lancamento": 2023,
        "tela": 6.7,
        "ram": 12,
        "armazenamento": 128,
        "bateria": 5050,
        "camera_principal": 50,
        "processador": "Tensor G3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro-new.jpg",
        "descricao": "IA do Google no seu melhor: Magic Eraser, Best Take e 7 anos de atualizações."
    },
    {
        "id": 21,
        "nome": "Google Pixel 8",
        "marca": "Google",
        "preco": 4999,
        "ano_lancamento": 2023,
        "tela": 6.2,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4575,
        "camera_principal": 50,
        "processador": "Tensor G3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg",
        "descricao": "A melhor experiência Android pura com câmera excepcional e IA integrada."
    },
    {
        "id": 22,
        "nome": "Google Pixel 7a",
        "marca": "Google",
        "preco": 2999,
        "ano_lancamento": 2023,
        "tela": 6.1,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4385,
        "camera_principal": 64,
        "processador": "Tensor G2",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg",
        "descricao": "Custo-benefício incrível com câmera de nível flagship e Android puro."
    },
    # OnePlus
    {
        "id": 23,
        "nome": "OnePlus 12",
        "marca": "OnePlus",
        "preco": 5999,
        "ano_lancamento": 2024,
        "tela": 6.82,
        "ram": 16,
        "armazenamento": 256,
        "bateria": 5400,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
        "descricao": "Carregamento de 100W, câmera Hasselblad e tela 2K com 120Hz ProXDR."
    },
    {
        "id": 24,
        "nome": "OnePlus Nord 3",
        "marca": "OnePlus",
        "preco": 2799,
        "ano_lancamento": 2023,
        "tela": 6.74,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Dimensity 9000",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-3.jpg",
        "descricao": "Performance de flagship em intermediário com carregamento de 80W e tela AMOLED."
    },
    # Realme
    {
        "id": 25,
        "nome": "Realme GT 5 Pro",
        "marca": "Realme",
        "preco": 3999,
        "ano_lancamento": 2024,
        "tela": 6.78,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5400,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/realme-gt5-pro.jpg",
        "descricao": "Flagship killer com Snapdragon 8 Gen 3, câmera periscópio e carga de 100W."
    },
    {
        "id": 26,
        "nome": "Realme 12 Pro+",
        "marca": "Realme",
        "preco": 2499,
        "ano_lancamento": 2024,
        "tela": 6.7,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Snapdragon 7s Gen 2",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg",
        "descricao": "Design luxury com câmera periscópio de zoom 3x e tela curva AMOLED."
    },
    {
        "id": 27,
        "nome": "Realme C55",
        "marca": "Realme",
        "preco": 999,
        "ano_lancamento": 2023,
        "tela": 6.72,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 64,
        "processador": "Helio G88",
        "sistema": "Android 13",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/realme-c55.jpg",
        "descricao": "Entrada com Mini Capsule inspirada no Dynamic Island e câmera de 64MP."
    },
    # Asus
    {
        "id": 28,
        "nome": "Asus ROG Phone 8 Pro",
        "marca": "Asus",
        "preco": 7999,
        "ano_lancamento": 2024,
        "tela": 6.78,
        "ram": 24,
        "armazenamento": 1024,
        "bateria": 5500,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg",
        "descricao": "O melhor celular gamer com 24GB de RAM, tela de 165Hz e refrigeração avançada."
    },
    {
        "id": 29,
        "nome": "Asus Zenfone 11 Ultra",
        "marca": "Asus",
        "preco": 5999,
        "ano_lancamento": 2024,
        "tela": 6.78,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5500,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-11-ultra.jpg",
        "descricao": "Flagship versátil com câmera gimbal de 3 eixos e bateria de longa duração."
    },
    # Nothing
    {
        "id": 30,
        "nome": "Nothing Phone (2)",
        "marca": "Nothing",
        "preco": 3499,
        "ano_lancamento": 2023,
        "tela": 6.7,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 4700,
        "camera_principal": 50,
        "processador": "Snapdragon 8+ Gen 1",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone2.jpg",
        "descricao": "Design transparente icônico com Glyph Interface e Android quase puro."
    },
    # === 2021 ===
    {
        "id": 31,
        "nome": "Samsung Galaxy S21 Ultra",
        "marca": "Samsung",
        "preco": 6499,
        "ano_lancamento": 2021,
        "tela": 6.8,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 108,
        "processador": "Exynos 2100",
        "sistema": "Android 11",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-ultra-5g.jpg",
        "descricao": "Topo de linha 2021 com câmera de 108MP, zoom 100x e suporte a S Pen."
    },
    {
        "id": 32,
        "nome": "Samsung Galaxy A52",
        "marca": "Samsung",
        "preco": 1899,
        "ano_lancamento": 2021,
        "tela": 6.5,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 4500,
        "camera_principal": 64,
        "processador": "Snapdragon 720G",
        "sistema": "Android 11",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a52.jpg",
        "descricao": "Intermediário campeão de vendas com tela AMOLED 90Hz e IP67."
    },
    {
        "id": 33,
        "nome": "iPhone 13 Pro Max",
        "marca": "Apple",
        "preco": 8799,
        "ano_lancamento": 2021,
        "tela": 6.7,
        "ram": 6,
        "armazenamento": 256,
        "bateria": 4352,
        "camera_principal": 12,
        "processador": "A15 Bionic",
        "sistema": "iOS 15",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro-max.jpg",
        "descricao": "Tela ProMotion 120Hz, modo Cinema e a melhor bateria já vista num iPhone."
    },
    {
        "id": 34,
        "nome": "iPhone 13",
        "marca": "Apple",
        "preco": 5499,
        "ano_lancamento": 2021,
        "tela": 6.1,
        "ram": 4,
        "armazenamento": 128,
        "bateria": 3227,
        "camera_principal": 12,
        "processador": "A15 Bionic",
        "sistema": "iOS 15",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
        "descricao": "Câmera dupla diagonal, modo Cinema e chip A15 ultrarrápido."
    },
    {
        "id": 35,
        "nome": "Xiaomi Mi 11",
        "marca": "Xiaomi",
        "preco": 4299,
        "ano_lancamento": 2021,
        "tela": 6.81,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 4600,
        "camera_principal": 108,
        "processador": "Snapdragon 888",
        "sistema": "Android 11",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-11.jpg",
        "descricao": "Tela WQHD+ de 120Hz, câmera de 108MP e carregamento de 55W."
    },
    {
        "id": 36,
        "nome": "Xiaomi Redmi Note 10 Pro",
        "marca": "Xiaomi",
        "preco": 1699,
        "ano_lancamento": 2021,
        "tela": 6.67,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5020,
        "camera_principal": 108,
        "processador": "Snapdragon 732G",
        "sistema": "Android 11",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note10-pro.jpg",
        "descricao": "Tela AMOLED 120Hz com câmera de 108MP no segmento intermediário."
    },
    {
        "id": 37,
        "nome": "Motorola Moto G60",
        "marca": "Motorola",
        "preco": 1499,
        "ano_lancamento": 2021,
        "tela": 6.8,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 6000,
        "camera_principal": 108,
        "processador": "Snapdragon 732G",
        "sistema": "Android 11",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g60.jpg",
        "descricao": "Bateria monstro de 6000mAh com câmera de 108MP e tela de 120Hz."
    },
    {
        "id": 38,
        "nome": "OnePlus 9 Pro",
        "marca": "OnePlus",
        "preco": 5499,
        "ano_lancamento": 2021,
        "tela": 6.7,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 4500,
        "camera_principal": 48,
        "processador": "Snapdragon 888",
        "sistema": "Android 11",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro.jpg",
        "descricao": "Câmera Hasselblad, carregamento de 65W e tela LTPO de 120Hz."
    },
    # === 2020 ===
    {
        "id": 39,
        "nome": "Samsung Galaxy S20 FE",
        "marca": "Samsung",
        "preco": 2799,
        "ano_lancamento": 2020,
        "tela": 6.5,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 4500,
        "camera_principal": 12,
        "processador": "Snapdragon 865",
        "sistema": "Android 10",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-fe-5g.jpg",
        "descricao": "Fan Edition com specs de flagship a preço acessível. Tela 120Hz e IP68."
    },
    {
        "id": 40,
        "nome": "Samsung Galaxy Note 20 Ultra",
        "marca": "Samsung",
        "preco": 7499,
        "ano_lancamento": 2020,
        "tela": 6.9,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 4500,
        "camera_principal": 108,
        "processador": "Exynos 990",
        "sistema": "Android 10",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note20-ultra-5g.jpg",
        "descricao": "Último da linha Note com S Pen de baixa latência e tela de 120Hz."
    },
    {
        "id": 41,
        "nome": "iPhone 12 Pro Max",
        "marca": "Apple",
        "preco": 8499,
        "ano_lancamento": 2020,
        "tela": 6.7,
        "ram": 6,
        "armazenamento": 256,
        "bateria": 3687,
        "camera_principal": 12,
        "processador": "A14 Bionic",
        "sistema": "iOS 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro-max-.jpg",
        "descricao": "Primeiro iPhone com 5G, design flat e sensor LiDAR para AR."
    },
    {
        "id": 42,
        "nome": "iPhone 12",
        "marca": "Apple",
        "preco": 4999,
        "ano_lancamento": 2020,
        "tela": 6.1,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 2815,
        "camera_principal": 12,
        "processador": "A14 Bionic",
        "sistema": "iOS 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg",
        "descricao": "Design renovado com bordas retas, tela OLED e chip A14."
    },
    {
        "id": 43,
        "nome": "Xiaomi Mi 10T Pro",
        "marca": "Xiaomi",
        "preco": 3299,
        "ano_lancamento": 2020,
        "tela": 6.67,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 108,
        "processador": "Snapdragon 865",
        "sistema": "Android 10",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-10t-pro-5g.jpg",
        "descricao": "Tela IPS de 144Hz com Snapdragon 865 e câmera de 108MP."
    },
    {
        "id": 44,
        "nome": "Motorola Moto G9 Plus",
        "marca": "Motorola",
        "preco": 1599,
        "ano_lancamento": 2020,
        "tela": 6.8,
        "ram": 4,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 64,
        "processador": "Snapdragon 730G",
        "sistema": "Android 10",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g9-plus.jpg",
        "descricao": "Tela grande de 6.8 polegadas com bateria de 5000mAh e carregamento turbo."
    },
    {
        "id": 45,
        "nome": "OnePlus 8T",
        "marca": "OnePlus",
        "preco": 3999,
        "ano_lancamento": 2020,
        "tela": 6.55,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4500,
        "camera_principal": 48,
        "processador": "Snapdragon 865",
        "sistema": "Android 11",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-8t.jpg",
        "descricao": "Carregamento Warp Charge de 65W, tela 120Hz e OxygenOS fluido."
    },
    # === 2019 ===
    {
        "id": 46,
        "nome": "Samsung Galaxy S10+",
        "marca": "Samsung",
        "preco": 4499,
        "ano_lancamento": 2019,
        "tela": 6.4,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4100,
        "camera_principal": 12,
        "processador": "Exynos 9820",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10-plus.jpg",
        "descricao": "Tela Infinity-O com câmera tripla e leitor de digitais ultrassônico."
    },
    {
        "id": 47,
        "nome": "Samsung Galaxy A50",
        "marca": "Samsung",
        "preco": 1299,
        "ano_lancamento": 2019,
        "tela": 6.4,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 4000,
        "camera_principal": 25,
        "processador": "Exynos 9610",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a50.jpg",
        "descricao": "Intermediário popular com tela AMOLED, leitor de digitais na tela e câmera tripla."
    },
    {
        "id": 48,
        "nome": "iPhone 11 Pro Max",
        "marca": "Apple",
        "preco": 7999,
        "ano_lancamento": 2019,
        "tela": 6.5,
        "ram": 4,
        "armazenamento": 256,
        "bateria": 3969,
        "camera_principal": 12,
        "processador": "A13 Bionic",
        "sistema": "iOS 13",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro-max.jpg",
        "descricao": "Primeira câmera tripla do iPhone com modo noturno e tela Super Retina XDR."
    },
    {
        "id": 49,
        "nome": "iPhone 11",
        "marca": "Apple",
        "preco": 4499,
        "ano_lancamento": 2019,
        "tela": 6.1,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 3110,
        "camera_principal": 12,
        "processador": "A13 Bionic",
        "sistema": "iOS 13",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11.jpg",
        "descricao": "Câmera dupla com ultra-wide, modo noturno e diversas opções de cores."
    },
    {
        "id": 50,
        "nome": "Xiaomi Mi 9",
        "marca": "Xiaomi",
        "preco": 2499,
        "ano_lancamento": 2019,
        "tela": 6.39,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 3300,
        "camera_principal": 48,
        "processador": "Snapdragon 855",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi9.jpg",
        "descricao": "Flagship acessível com câmera tripla de 48MP e Snapdragon 855."
    },
    {
        "id": 51,
        "nome": "Motorola One Vision",
        "marca": "Motorola",
        "preco": 1499,
        "ano_lancamento": 2019,
        "tela": 6.3,
        "ram": 4,
        "armazenamento": 128,
        "bateria": 3500,
        "camera_principal": 48,
        "processador": "Exynos 9609",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-one-vision.jpg",
        "descricao": "Tela cinema 21:9 com Night Vision e Android One puro."
    },
    {
        "id": 52,
        "nome": "OnePlus 7 Pro",
        "marca": "OnePlus",
        "preco": 3999,
        "ano_lancamento": 2019,
        "tela": 6.67,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 4000,
        "camera_principal": 48,
        "processador": "Snapdragon 855",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-7-pro.jpg",
        "descricao": "Tela sem notch de 90Hz com câmera pop-up e Warp Charge 30."
    },
    # === 2018 ===
    {
        "id": 53,
        "nome": "Samsung Galaxy S9+",
        "marca": "Samsung",
        "preco": 3999,
        "ano_lancamento": 2018,
        "tela": 6.2,
        "ram": 6,
        "armazenamento": 64,
        "bateria": 3500,
        "camera_principal": 12,
        "processador": "Exynos 9810",
        "sistema": "Android 8",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s9-plus.jpg",
        "descricao": "Câmera com abertura variável, Super Slow Motion e tela Infinity Display."
    },
    {
        "id": 54,
        "nome": "Samsung Galaxy Note 9",
        "marca": "Samsung",
        "preco": 5499,
        "ano_lancamento": 2018,
        "tela": 6.4,
        "ram": 8,
        "armazenamento": 512,
        "bateria": 4000,
        "camera_principal": 12,
        "processador": "Exynos 9810",
        "sistema": "Android 8",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note9-.jpg",
        "descricao": "S Pen com Bluetooth, bateria de 4000mAh e até 512GB de armazenamento."
    },
    {
        "id": 55,
        "nome": "iPhone XS Max",
        "marca": "Apple",
        "preco": 7499,
        "ano_lancamento": 2018,
        "tela": 6.5,
        "ram": 4,
        "armazenamento": 256,
        "bateria": 3174,
        "camera_principal": 12,
        "processador": "A12 Bionic",
        "sistema": "iOS 12",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-xs-max.jpg",
        "descricao": "Maior iPhone da época com tela OLED de 6.5 polegadas e Face ID."
    },
    {
        "id": 56,
        "nome": "iPhone XR",
        "marca": "Apple",
        "preco": 4299,
        "ano_lancamento": 2018,
        "tela": 6.1,
        "ram": 3,
        "armazenamento": 64,
        "bateria": 2942,
        "camera_principal": 12,
        "processador": "A12 Bionic",
        "sistema": "iOS 12",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-xr.jpg",
        "descricao": "iPhone colorido e acessível com tela Liquid Retina e excelente bateria."
    },
    {
        "id": 57,
        "nome": "Xiaomi Mi 8",
        "marca": "Xiaomi",
        "preco": 1999,
        "ano_lancamento": 2018,
        "tela": 6.21,
        "ram": 6,
        "armazenamento": 64,
        "bateria": 3400,
        "camera_principal": 12,
        "processador": "Snapdragon 845",
        "sistema": "Android 8",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi8.jpg",
        "descricao": "Flagship com GPS dual-frequency, câmera avaliada com 105 no DxOMark."
    },
    {
        "id": 58,
        "nome": "Motorola Moto G6 Plus",
        "marca": "Motorola",
        "preco": 1199,
        "ano_lancamento": 2018,
        "tela": 5.9,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 3200,
        "camera_principal": 12,
        "processador": "Snapdragon 630",
        "sistema": "Android 8",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g6-plus.jpg",
        "descricao": "Intermediário com design em vidro, tela Full HD+ e câmera dupla."
    },
    {
        "id": 59,
        "nome": "OnePlus 6T",
        "marca": "OnePlus",
        "preco": 2999,
        "ano_lancamento": 2018,
        "tela": 6.41,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 3700,
        "camera_principal": 16,
        "processador": "Snapdragon 845",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-6t.jpg",
        "descricao": "Leitor de digitais na tela, notch gota d'água e OxygenOS ultrafluido."
    },
    {
        "id": 60,
        "nome": "Google Pixel 3",
        "marca": "Google",
        "preco": 3499,
        "ano_lancamento": 2018,
        "tela": 5.5,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 2915,
        "camera_principal": 12,
        "processador": "Snapdragon 845",
        "sistema": "Android 9",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-3.jpg",
        "descricao": "Melhor câmera de 2018 com Night Sight e Android puro do Google."
    },
]

# Listas de opções para filtros
MARCAS = sorted(list(set(phone["marca"] for phone in PHONES)))
ANOS = sorted(list(set(phone["ano_lancamento"] for phone in PHONES)), reverse=True)
