"""
Base de dados de celulares para recomendação.
Contém informações detalhadas sobre diversos modelos.
"""

PHONES = [
    # Samsung
    {
        "id": 1,
        "nome": "Samsung Galaxy S24 Ultra",
        "marca": "Samsung",
        "preco": 8499,
        "ano_lancamento": 2024,
        "tela": 6.8,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 200,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g.jpg",
        "descricao": "O topo de linha da Samsung com S Pen integrada, câmera de 200MP e tela AMOLED de 6.8 polegadas."
    },
    {
        "id": 2,
        "nome": "Samsung Galaxy S24",
        "marca": "Samsung",
        "preco": 5499,
        "ano_lancamento": 2024,
        "tela": 6.2,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4000,
        "camera_principal": 50,
        "processador": "Exynos 2400",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g.jpg",
        "descricao": "Compacto e poderoso, com IA integrada e Galaxy AI para produtividade."
    },
    {
        "id": 3,
        "nome": "Samsung Galaxy A55",
        "marca": "Samsung",
        "preco": 2799,
        "ano_lancamento": 2024,
        "tela": 6.6,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Exynos 1480",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg",
        "descricao": "Intermediário premium com tela Super AMOLED e resistência à água IP67."
    },
    {
        "id": 4,
        "nome": "Samsung Galaxy A35",
        "marca": "Samsung",
        "preco": 1999,
        "ano_lancamento": 2024,
        "tela": 6.6,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Exynos 1380",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg",
        "descricao": "Ótimo custo-benefício com tela AMOLED de 120Hz e bateria de longa duração."
    },
    {
        "id": 5,
        "nome": "Samsung Galaxy A15",
        "marca": "Samsung",
        "preco": 1099,
        "ano_lancamento": 2024,
        "tela": 6.5,
        "ram": 4,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Helio G99",
        "sistema": "Android 14",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15.jpg",
        "descricao": "Entrada com tela AMOLED grande e bateria generosa para o dia todo."
    },
    # Apple
    {
        "id": 6,
        "nome": "iPhone 15 Pro Max",
        "marca": "Apple",
        "preco": 9999,
        "ano_lancamento": 2023,
        "tela": 6.7,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 4441,
        "camera_principal": 48,
        "processador": "A17 Pro",
        "sistema": "iOS 17",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
        "descricao": "O iPhone mais avançado com chip A17 Pro, titânio e câmera periscópio com zoom 5x."
    },
    {
        "id": 7,
        "nome": "iPhone 15",
        "marca": "Apple",
        "preco": 6499,
        "ano_lancamento": 2023,
        "tela": 6.1,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 3349,
        "camera_principal": 48,
        "processador": "A16 Bionic",
        "sistema": "iOS 17",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
        "descricao": "Design com Dynamic Island, câmera de 48MP e conector USB-C."
    },
    {
        "id": 8,
        "nome": "iPhone 14",
        "marca": "Apple",
        "preco": 4999,
        "ano_lancamento": 2022,
        "tela": 6.1,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 3279,
        "camera_principal": 12,
        "processador": "A15 Bionic",
        "sistema": "iOS 16",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg",
        "descricao": "Design elegante com detecção de acidentes e modo Ação para vídeos estabilizados."
    },
    {
        "id": 9,
        "nome": "iPhone SE (2022)",
        "marca": "Apple",
        "preco": 3499,
        "ano_lancamento": 2022,
        "tela": 4.7,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 2018,
        "camera_principal": 12,
        "processador": "A15 Bionic",
        "sistema": "iOS 15",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg",
        "descricao": "iPhone compacto e acessível com chip potente e Touch ID."
    },
    # Xiaomi
    {
        "id": 10,
        "nome": "Xiaomi 14 Ultra",
        "marca": "Xiaomi",
        "preco": 7499,
        "ano_lancamento": 2024,
        "tela": 6.73,
        "ram": 16,
        "armazenamento": 512,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg",
        "descricao": "Câmera Leica profissional com sensor de 1 polegada e gravação 8K."
    },
    {
        "id": 11,
        "nome": "Xiaomi 14",
        "marca": "Xiaomi",
        "preco": 4999,
        "ano_lancamento": 2024,
        "tela": 6.36,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 4610,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg",
        "descricao": "Compacto premium com câmera Leica e tela LTPO AMOLED de 120Hz."
    },
    {
        "id": 12,
        "nome": "Xiaomi Redmi Note 13 Pro",
        "marca": "Xiaomi",
        "preco": 2299,
        "ano_lancamento": 2024,
        "tela": 6.67,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5100,
        "camera_principal": 200,
        "processador": "Snapdragon 7s Gen 2",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-5g.jpg",
        "descricao": "Câmera de 200MP incrível em um intermediário com carregamento de 67W."
    },
    {
        "id": 13,
        "nome": "Xiaomi Redmi Note 13",
        "marca": "Xiaomi",
        "preco": 1499,
        "ano_lancamento": 2024,
        "tela": 6.67,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 108,
        "processador": "Snapdragon 685",
        "sistema": "Android 13",
        "cinco_g": False,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-4g.jpg",
        "descricao": "Tela AMOLED de 120Hz com câmera de 108MP a um preço acessível."
    },
    {
        "id": 14,
        "nome": "Xiaomi POCO X6 Pro",
        "marca": "Xiaomi",
        "preco": 2499,
        "ano_lancamento": 2024,
        "tela": 6.67,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 64,
        "processador": "Dimensity 8300 Ultra",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro-5g.jpg",
        "descricao": "Performance de flagship com carregamento turbo de 67W e tela Flow AMOLED."
    },
    # Motorola
    {
        "id": 15,
        "nome": "Motorola Edge 50 Ultra",
        "marca": "Motorola",
        "preco": 5499,
        "ano_lancamento": 2024,
        "tela": 6.7,
        "ram": 16,
        "armazenamento": 512,
        "bateria": 4500,
        "camera_principal": 50,
        "processador": "Snapdragon 8s Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg",
        "descricao": "Acabamento em madeira ou couro, câmera periscópio e tela pOLED de 144Hz."
    },
    {
        "id": 16,
        "nome": "Motorola Edge 40 Neo",
        "marca": "Motorola",
        "preco": 2499,
        "ano_lancamento": 2023,
        "tela": 6.55,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Dimensity 7030",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-40-neo.jpg",
        "descricao": "Intermediário elegante com tela pOLED de 144Hz e carregamento de 68W."
    },
    {
        "id": 17,
        "nome": "Motorola Moto G84",
        "marca": "Motorola",
        "preco": 1799,
        "ano_lancamento": 2023,
        "tela": 6.55,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Snapdragon 695",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g84.jpg",
        "descricao": "Tela pOLED em intermediário com som estéreo Dolby Atmos e design fino."
    },
    {
        "id": 18,
        "nome": "Motorola Moto G54",
        "marca": "Motorola",
        "preco": 1299,
        "ano_lancamento": 2023,
        "tela": 6.5,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Dimensity 7020",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g54-5g.jpg",
        "descricao": "5G acessível com som estéreo e bateria para dois dias de uso."
    },
    {
        "id": 19,
        "nome": "Motorola Moto E22",
        "marca": "Motorola",
        "preco": 799,
        "ano_lancamento": 2022,
        "tela": 6.5,
        "ram": 4,
        "armazenamento": 64,
        "bateria": 4020,
        "camera_principal": 16,
        "processador": "Helio G37",
        "sistema": "Android 12",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-e22.jpg",
        "descricao": "Smartphone básico e confiável para tarefas do dia a dia com tela de 90Hz."
    },
    # Google Pixel
    {
        "id": 20,
        "nome": "Google Pixel 8 Pro",
        "marca": "Google",
        "preco": 6999,
        "ano_lancamento": 2023,
        "tela": 6.7,
        "ram": 12,
        "armazenamento": 128,
        "bateria": 5050,
        "camera_principal": 50,
        "processador": "Tensor G3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro-new.jpg",
        "descricao": "IA do Google no seu melhor: Magic Eraser, Best Take e 7 anos de atualizações."
    },
    {
        "id": 21,
        "nome": "Google Pixel 8",
        "marca": "Google",
        "preco": 4999,
        "ano_lancamento": 2023,
        "tela": 6.2,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4575,
        "camera_principal": 50,
        "processador": "Tensor G3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg",
        "descricao": "A melhor experiência Android pura com câmera excepcional e IA integrada."
    },
    {
        "id": 22,
        "nome": "Google Pixel 7a",
        "marca": "Google",
        "preco": 2999,
        "ano_lancamento": 2023,
        "tela": 6.1,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 4385,
        "camera_principal": 64,
        "processador": "Tensor G2",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg",
        "descricao": "Custo-benefício incrível com câmera de nível flagship e Android puro."
    },
    # OnePlus
    {
        "id": 23,
        "nome": "OnePlus 12",
        "marca": "OnePlus",
        "preco": 5999,
        "ano_lancamento": 2024,
        "tela": 6.82,
        "ram": 16,
        "armazenamento": 256,
        "bateria": 5400,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
        "descricao": "Carregamento de 100W, câmera Hasselblad e tela 2K com 120Hz ProXDR."
    },
    {
        "id": 24,
        "nome": "OnePlus Nord 3",
        "marca": "OnePlus",
        "preco": 2799,
        "ano_lancamento": 2023,
        "tela": 6.74,
        "ram": 8,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Dimensity 9000",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-3.jpg",
        "descricao": "Performance de flagship em intermediário com carregamento de 80W e tela AMOLED."
    },
    # Realme
    {
        "id": 25,
        "nome": "Realme GT 5 Pro",
        "marca": "Realme",
        "preco": 3999,
        "ano_lancamento": 2024,
        "tela": 6.78,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5400,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/realme-gt5-pro.jpg",
        "descricao": "Flagship killer com Snapdragon 8 Gen 3, câmera periscópio e carga de 100W."
    },
    {
        "id": 26,
        "nome": "Realme 12 Pro+",
        "marca": "Realme",
        "preco": 2499,
        "ano_lancamento": 2024,
        "tela": 6.7,
        "ram": 8,
        "armazenamento": 256,
        "bateria": 5000,
        "camera_principal": 50,
        "processador": "Snapdragon 7s Gen 2",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg",
        "descricao": "Design luxury com câmera periscópio de zoom 3x e tela curva AMOLED."
    },
    {
        "id": 27,
        "nome": "Realme C55",
        "marca": "Realme",
        "preco": 999,
        "ano_lancamento": 2023,
        "tela": 6.72,
        "ram": 6,
        "armazenamento": 128,
        "bateria": 5000,
        "camera_principal": 64,
        "processador": "Helio G88",
        "sistema": "Android 13",
        "cinco_g": False,
        "nfc": False,
        "resistencia_agua": False,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/realme-c55.jpg",
        "descricao": "Entrada com Mini Capsule inspirada no Dynamic Island e câmera de 64MP."
    },
    # Asus
    {
        "id": 28,
        "nome": "Asus ROG Phone 8 Pro",
        "marca": "Asus",
        "preco": 7999,
        "ano_lancamento": 2024,
        "tela": 6.78,
        "ram": 24,
        "armazenamento": 1024,
        "bateria": 5500,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg",
        "descricao": "O melhor celular gamer com 24GB de RAM, tela de 165Hz e refrigeração avançada."
    },
    {
        "id": 29,
        "nome": "Asus Zenfone 11 Ultra",
        "marca": "Asus",
        "preco": 5999,
        "ano_lancamento": 2024,
        "tela": 6.78,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 5500,
        "camera_principal": 50,
        "processador": "Snapdragon 8 Gen 3",
        "sistema": "Android 14",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-11-ultra.jpg",
        "descricao": "Flagship versátil com câmera gimbal de 3 eixos e bateria de longa duração."
    },
    # Nothing
    {
        "id": 30,
        "nome": "Nothing Phone (2)",
        "marca": "Nothing",
        "preco": 3499,
        "ano_lancamento": 2023,
        "tela": 6.7,
        "ram": 12,
        "armazenamento": 256,
        "bateria": 4700,
        "camera_principal": 50,
        "processador": "Snapdragon 8+ Gen 1",
        "sistema": "Android 13",
        "cinco_g": True,
        "nfc": True,
        "resistencia_agua": True,
        "imagem": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone2.jpg",
        "descricao": "Design transparente icônico com Glyph Interface e Android quase puro."
    },
]

# Listas de opções para filtros
MARCAS = sorted(list(set(phone["marca"] for phone in PHONES)))
ANOS = sorted(list(set(phone["ano_lancamento"] for phone in PHONES)), reverse=True)
